# Common community mapping for Walmart Department IDs (Guesstimated)
# Although the dataset is anonymized, these are frequently used categories for analysis.

DEPT_MAPPING = {
    1: "Bedding / Bath",
    2: "Health / Beauty",
    3: "Stationery",
    4: "Household Chemicals",
    5: "Home Office",
    6: "Personalized / Crafts",
    7: "Jewelry",
    8: "Photo / Electronics",
    9: "Electronics",
    10: "Automotive",
    11: "Hardware",
    12: "Paint / Home Decor",
    13: "Household Paper",
    14: "Cook & Dine",
    16: "Lawn & Garden",
    17: "Home Decor",
    18: "Seasonal",
    19: "Crafts / Fabrics",
    20: "Bath & Shower",
    21: "Books",
    22: "Bedding",
    23: "Furniture",
    24: "Apparel - Men's",
    25: "Apparel - Shoes",
    26: "Apparel - Women's",
    27: "Apparel - Kids",
    28: "Apparel - Accessories",
    29: "Apparel - Intimates",
    30: "Apparel - Hosiery",
    31: "Apparel - Jewelry",
    32: "Apparel - Plus Size",
    33: "Apparel - Maternity",
    34: "Apparel - Juniors",
    35: "Apparel - Men's Suits",
    36: "Apparel - Outerwear",
    37: "Apparel - Sportswear",
    38: "Apparel - Sleepwear",
    40: "Pharmacy / OTC",
    42: "Automotive Services",
    44: "Personal Care",
    46: "Cosmetics",
    49: "Optical",
    52: "Pets",
    55: "Celebrations",
    56: "Horticulture",
    59: "Gas Station",
    60: "Financial Services",
    67: "Celebration Essentials",
    71: "Furniture Accessories",
    72: "Electronics / Entertainment",
    74: "Housewares",
    79: "Cell Phones",
    80: "Bakery",
    81: "Deli",
    82: "Impulse / Snacks",
    83: "Seafood",
    85: "Meat",
    87: "Wireless",
    90: "Dairy",
    91: "Frozen Foods",
    92: "Grocery",
    93: "Meat / Poultry",
    94: "Produce",
    95: "Snacks / Beverages",
    96: "Liquor",
    97: "Meat - Service",
    98: "Bakery - Service",
    99: "Office / Other"
}

def get_dept_name(dept_id):
    return DEPT_MAPPING.get(dept_id, f"Department {dept_id}")
